config/routes.rb
Rails.application.routes.draw do
  #get 'cart/index'
  #get 'cart/create'
  #get 'cart/update'
  #get 'cart/destroy'
  get 'order/index'
  get 'contact/show'
  get 'about/show'
  get 'about', to: 'about#show'
  get 'contact', to: 'contact#show'
  #get 'shoes/index'
  #get 'shoes/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :shoes, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  root 'shoes#index'
  resources :cart, only: [:create, :checkout, :destroy, :index, :update]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/about.rb
class About < ApplicationRecord
  validates :content, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "updated_at"]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
  ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :shoes

  validates :brand_name, presence: true, uniqueness: true

  def self.ransackable_attributes(auth_object = nil)
    ["brand_name", "created_at", "id", "id_value", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["shoes"]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :content, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "updated_at"]
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :shoe
  has_many :order_items

  validates :total_amount, :subtotal, presence: true
  validates :pst, :gst, :hst, :total_amount, numericality: { greater_than_or_equal_to: 0}

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "gst", "hst", "id", "id_value", "pst", "shoe_id", "subtotal", "total_amount", "updated_at", "user_id"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :users
end

app/models/sale_price.rb
class SalePrice < ApplicationRecord
  has_many :shoes

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "sale_date", "sale_item", "sale_price", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["shoes"]
  end
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  validates :shoe_type, :price, :shoe_model, :size, :gender, :material, :quantity_available, presence: true

  belongs_to :brand
  belongs_to :sale_price
  has_many :orders

  def self.ransackable_attributes(auth_object = nil)
    ["color", "created_at", "description", "gender", "id", "id_value", "material", "price", "quantity_available", "shoe_model", "shoe_type", "size", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["brand", "sale_price", "orders"]
  end

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :region
  has_many :orders

  def self.ransackable_associations(auth_object = nil)
    ["orders", "region"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "email", "encrypted_password", "first_name", "id", "id_value", "last_name", "region_id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
    @about = About.all.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
    @contact = Contact.all.first
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def index
    @shoes = Shoe.includes(:brand).page(params[:page]).per(12)
  end

  def show
    @shoe = Shoe.includes(:brand).find(params[:id])
  end

  def search
    @keywords = params[:keywords]
    @brand_id = params[:brand_id]

    @shoes = Shoe.includes(:brand)

    if @keywords.present?
      wildcard_search = "%#{@keywords}%"
      @shoes = @shoes.where("shoe_model LIKE ? OR description LIKE ?", wildcard_search, wildcard_search)
    end

    if @brand_id.present?
      @shoes = @shoes.where(brand_id: @brand_id)
    end

    @shoes = @shoes.page(params[:page]).per(12)


  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/about/show.html.erb
<h1>About Us</h1>
<p><%= @about.content %></p>

app/views/contact/show.html.erb
<h1>Contact</h1>
<p><%= @contact.content %></p>

app/views/layouts/_menu.html.erb
<nav class="navbar">
  <div class="navbar-menu">
    <%= link_to 'Home', shoes_path, class: "navbar-item"%>
    <%= link_to 'About Us', about_path, class: "navbar-item"%>
    <%= link_to 'Contact', contact_path, class: "navbar-item"%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>

  <body>
    <%= render "layouts/menu" %>
      <div class="container">
        <%= form_with(url: search_shoes_path, method: :get, local: true) do |f| %>
        <div class="field is-grouped mb-5">
          <%= f.text_field :keywords, class: "input", placeholder: 'Search by keyword' %>
          <%= f.select :brand_id, Brand.all.map { |b| [b.brand_name, b.id] }, { prompt: "Select Brand" }, class: "select" %>
          <div class="control">
            <%= f.submit "Search", class: "button is-primary" %>
          </div>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shoes/_shoe.html.erb
<div class="card">
  <div class="card-content">
      <% if shoe.image.present? %>
        <div class="media-left">
          <div class="card-image">
            <%= image_tag(shoe.image, alt: "#{shoe.shoe_model} image", size: "600x400") %>
          </div>
        </div>
      <% end %>
        <div class="media-content">
          <strong><%= link_to shoe.shoe_model, shoe %></strong>
          <p class="subtitle is-6">Cost: <%= number_to_currency(shoe.price) %></p>
          <% if shoe.sale_price.sale_price.present? %>
            <strong>Sale Price: <%= number_to_currency(shoe.sale_price.sale_price) %></strong>
          <% end %>
          <hr>
          <p class="subtitle is-6">Stocks: <%= shoe.quantity_available %></p>
          <p class="subtitle is-6">Brand: <%= shoe.brand.brand_name %></p>
          <p class="subtitle is-6">Type: <%= shoe.shoe_type %></p>
          <p class="subtitle is-6">Color: <%= shoe.color %></p>
          <p class="subtitle is-6">Gender: <%= shoe.gender %></p>
          <p class="subtitle is-6">Size: <%= shoe.size %></p>
          <p class="subtitle is-6"><strong>Description:</strong></p>
          <p><%= shoe.description %></p>
        </div>
  </div>
</div>

app/views/shoes/index.html.erb
<div class="columns is-multiline is-mobile">
  <% @shoes.each do |shoe| %>
      <div class="column is-one-quarter">
        <%= render shoe %>
      </div>
  <% end %>
</div>
<div class="columns is-centered">
  <%= paginate @shoes %>
</div>

app/views/shoes/search.html.erb
<% if @keywords.present? %>
  <p>Found <%= pluralize(@shoes.total_count, 'shoe') %> when searching for: <%= @keywords %></p>
<% end %>

<div class="columns is-multiline is-mobile">
      <% @shoes.each do |shoe| %>
        <div class="column is-one-quarter">
          <div class="card">
            <div class="card-content">
              <% if shoe.image.present? %>
                  <div class="card-image">
                    <%= image_tag(shoe.image, alt: "#{shoe.shoe_model} Image", size: '600x400') %>
                  </div>
              <% end %>

              <div class="media-content">
                <strong><%= link_to shoe.shoe_model, shoe %></strong>
                <p class="subtitle is-6">Cost: <%= number_to_currency(shoe.price) %></p>
                <hr>
                <p class="subtitle is-6">Stocks: <%= shoe.quantity_available %></p>
                <p class="subtitle is-6">Brand: <%= shoe.brand.brand_name %></p>
                <p class="subtitle is-6">Type: <%= shoe.shoe_type %></p>
                <p class="subtitle is-6">Color: <%= shoe.color %></p>
                <p class="subtitle is-6">Gender: <%= shoe.gender %></p>
                <p class="subtitle is-6">Size: <%= shoe.size %></p>
                <p class="subtitle is-6">Description: <%= shoe.description %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="columns is-centered">
    <%= paginate @shoes %>
</div>

app/views/shoes/show.html.erb
<div class="columns is-centered">
  <div class="column is-half">
    <div class="card">
      <div class="card-content">
        <% if @shoe.image.present? %>
          <div class="media-left">
            <div class="card-image">
              <%= image_tag(@shoe.image, alt: "#{@shoe.shoe_model} image", size: "600x400") %>
            </div>
          </div>
        <% end %>

        <strong><%= @shoe.shoe_model %></strong>
        <p class="subtitle is-6"><%= @shoe.shoe_type %></p>
        <p class="subtitle is-6">Price: <%= number_to_currency(@shoe.price) %></p>
        <p class="subtitle is-6">Gender: <%= @shoe.gender %></p>
        <p class="subtitle is-6">Stock Quantity: <%= @shoe.quantity_available %></p>
        <p class="subtitle is-6">Color: <%= @shoe.color %></p>
        <% if @shoe.description.present? %>
          <p class="subtitle is-6"><strong>Description:</strong></p>
          <div class="content">
            <% @shoe.description.split("\n").each do |sentence| %>
              <p><%= sentence.strip %></p>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>